### ISSUE TITLE
[TODO]优化项

### ISSUE THREAD

**Issue by Abeautifulsnow** [GoToUse/codeLines#1]
- [ ] 支持不包括指定后缀的文件
- [ ] 优化输出
  - [ ] 顺序和倒序排序输出
  - [ ] 按照一定规则排序
- [ ] 支持指定多个文件后缀去匹配文件的行数统计
- [ ] 代码错误处理不够细致，有一些错误返回不易理解
- [x] 缺陷：convertToAbsPath只针对 `.` 和 `./` 做了Abs绝对路径转化。
- [x] exclude 目录支持部分目录作为关键词过滤，目前只支持相对路径下的精准过滤，比如 `authtoken/migrations` 可以过滤掉，但 `migrations` 不能过滤掉包含它的目录。
- [ ] 统计文件行数不包括:
  - [x] 空行「目前是包括的」
  - [ ] 输出包括总行数
  - [ ] 注释「注释需要根据不同语言设定，单行和多行注释」
- [ ] list所有的文件类型
- [ ] 聚合不同语言的文件行数(包括code, blank, comment 等)

**Comment by Abeautifulsnow** [comment]
参考https://github.com/hhatto/gocloc
